export const data = [
    {
      "District": "Lucknow",
      "Total Plays": "17982",
      "Total Devices": "3019",
      "Content Plays from new devices": "4398",
      "New Devices": "468",
      "Content Plays from old devices": "13584",
      "Old Devices": "2551",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Allahabad",
      "Total Plays": "7368",
      "Total Devices": "1229",
      "Content Plays from new devices": "1406",
      "New Devices": "175",
      "Content Plays from old devices": "5962",
      "Old Devices": "1054",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Aligarh",
      "Total Plays": "6085",
      "Total Devices": "881",
      "Content Plays from new devices": "907",
      "New Devices": "115",
      "Content Plays from old devices": "5178",
      "Old Devices": "766",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Azamgarh",
      "Total Plays": "5294",
      "Total Devices": "807",
      "Content Plays from new devices": "1082",
      "New Devices": "144",
      "Content Plays from old devices": "4212",
      "Old Devices": "663",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Jaunpur",
      "Total Plays": "4973",
      "Total Devices": "835",
      "Content Plays from new devices": "913",
      "New Devices": "130",
      "Content Plays from old devices": "4060",
      "Old Devices": "705",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Bijnor",
      "Total Plays": "4158",
      "Total Devices": "679",
      "Content Plays from new devices": "453",
      "New Devices": "69",
      "Content Plays from old devices": "3705",
      "Old Devices": "610",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Kanpur Nagar",
      "Total Plays": "3976",
      "Total Devices": "671",
      "Content Plays from new devices": "831",
      "New Devices": "122",
      "Content Plays from old devices": "3145",
      "Old Devices": "549",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Ghaziabad",
      "Total Plays": "3949",
      "Total Devices": "481",
      "Content Plays from new devices": "746",
      "New Devices": "106",
      "Content Plays from old devices": "3203",
      "Old Devices": "375",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Ghazipur",
      "Total Plays": "3870",
      "Total Devices": "664",
      "Content Plays from new devices": "495",
      "New Devices": "67",
      "Content Plays from old devices": "3375",
      "Old Devices": "597",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Lakhimpur",
      "Total Plays": "3843",
      "Total Devices": "723",
      "Content Plays from new devices": "470",
      "New Devices": "72",
      "Content Plays from old devices": "3373",
      "Old Devices": "651",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Agra",
      "Total Plays": "3822",
      "Total Devices": "455",
      "Content Plays from new devices": "1208",
      "New Devices": "104",
      "Content Plays from old devices": "2614",
      "Old Devices": "351",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Farrukhabad",
      "Total Plays": "3674",
      "Total Devices": "596",
      "Content Plays from new devices": "666",
      "New Devices": "134",
      "Content Plays from old devices": "3008",
      "Old Devices": "462",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Bulandshehr",
      "Total Plays": "3324",
      "Total Devices": "569",
      "Content Plays from new devices": "513",
      "New Devices": "54",
      "Content Plays from old devices": "2811",
      "Old Devices": "515",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Mathura",
      "Total Plays": "3302",
      "Total Devices": "445",
      "Content Plays from new devices": "744",
      "New Devices": "75",
      "Content Plays from old devices": "2558",
      "Old Devices": "370",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Varanasi",
      "Total Plays": "3163",
      "Total Devices": "556",
      "Content Plays from new devices": "587",
      "New Devices": "99",
      "Content Plays from old devices": "2576",
      "Old Devices": "457",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Ballia",
      "Total Plays": "3158",
      "Total Devices": "516",
      "Content Plays from new devices": "597",
      "New Devices": "98",
      "Content Plays from old devices": "2561",
      "Old Devices": "418",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Fatehpur",
      "Total Plays": "3105",
      "Total Devices": "534",
      "Content Plays from new devices": "510",
      "New Devices": "85",
      "Content Plays from old devices": "2595",
      "Old Devices": "449",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Unnao",
      "Total Plays": "3094",
      "Total Devices": "485",
      "Content Plays from new devices": "977",
      "New Devices": "131",
      "Content Plays from old devices": "2117",
      "Old Devices": "354",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Gautam Buddh Nagar",
      "Total Plays": "2998",
      "Total Devices": "278",
      "Content Plays from new devices": "775",
      "New Devices": "49",
      "Content Plays from old devices": "2223",
      "Old Devices": "229",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Ambedkar Nagar",
      "Total Plays": "2855",
      "Total Devices": "402",
      "Content Plays from new devices": "1108",
      "New Devices": "119",
      "Content Plays from old devices": "1747",
      "Old Devices": "283",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Saharanpur",
      "Total Plays": "2746",
      "Total Devices": "433",
      "Content Plays from new devices": "595",
      "New Devices": "56",
      "Content Plays from old devices": "2151",
      "Old Devices": "377",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    },
    {
      "District": "Bareilly",
      "Total Plays": "2626",
      "Total Devices": "527",
      "Content Plays from new devices": "558",
      "New Devices": "82",
      "Content Plays from old devices": "2068",
      "Old Devices": "445",
      "Goal of content plays": "2519",
      "Goal of Devices": "405"
    }
  ]